### PR TITLE
Fix README.md

### PR DESCRIPTION
**Pull request by supertong**

### CODE REVIEW

**Comment by 1999** [comment]
LGTM

**Comment by torifat** [comment]
> `import * as betterAjvErrors from 'better-ajv-errors';`
BTW, why do we need this? We have `add-module-exports`. And, things are exported as default. Isn't it a TypeScript specific thing?

**Comment by supertong** [comment]
@torifat My mistake, I will revert it back and update the typescript file.

**Comment by torifat** [comment]
@supertong No worries 😄 BTW, if it's working fine then I can release a new version.

**Comment by supertong** [comment]
@torifat yep, I think you can do a release now because I have merged the other PR.

**Pull request merged**
